### ISSUE TITLE
feat: add reservation endpoint

### ISSUE THREAD

**Issue by Pablito2020** [RefuAPP/refuapp-backend#4]
- [x] **POST /reservation**
- [x] **GET /reservation/:id**
- [x] **GET /reservations/user/:id**
- [x] **GET /reservations/refuge/:id/date/:date**
- [x] **GET /reservations/refuge/:id/user/:id**
- [x] **PUT /reservation/:id**
- [x] **DELETE /reservation/:id**

**Comment by oriolagobat** [comment]
Refer to `RefuAPP/refuapp-reports/api-routes/reservation.md` repository for further documentation
